### ISSUE TITLE
LSTM

### ISSUE THREAD

**Issue by maryamag85** [chirag126/Automatic_Alzheimer_Detection#1]
Hi, thank you for the code, I would like to know how can I run LSTM.py code. it seems it has some errors.

**Comment by chirag-agarwall** [comment]
Hello maryamag85, can you tell me what is the error you are getting?

**Comment by maryamag85** [comment]
I can not find anywhere in the code which you run the LSTM. I see that you switch between various classifiers of LR,DT,SVM and RF. Am I wrong?
Maybe I have to ask if you have implemented the LSTM for this problem or not.

**Comment by chirag-agarwall** [comment]
Yes, you are right. I did not merge that implementation to the current repo.
